### ISSUE TITLE
500 error on article pages

### ISSUE THREAD

**Issue by laurosilvacom** [eggheadio/egghead-next#574]
We are getting a 500 error on all the article pages (e.g. [Write A Plugin For Tailwind CSS](https://egghead.io/blog/write-a-plugin-for-tailwind-css)). It looks like the recent PR https://github.com/eggheadio/egghead-next/pull/564 caused the issue. 

Here's the [build](https://egghead-io-nextjs-git-depfu-batchallyarn2021-04-19-eggheadio1.vercel.app/blog/write-a-plugin-for-tailwind-css) from https://github.com/eggheadio/egghead-next/pull/564 erroring out. And this is the previous [build](https://egghead-io-nextjs-git-zj-update-jumbotron-links-eggheadio1.vercel.app/blog/write-a-plugin-for-tailwind-css)  from https://github.com/eggheadio/egghead-next/pull/572 where it's running smoothly. 

I was not able to reproduce the error in development, I even tried running a production mode and clearing the `.next`. Nothing. 

Vojta got the following error in development:

![image](https://user-images.githubusercontent.com/57044804/115613059-cea02180-a2a0-11eb-97e0-8fc762d88135.png)

**Comment by joelhooks** [comment]
```
[GET] /blog/why-bother-with-headless-wordpress
17:17:31:54
2021-04-22T00:17:41.853Z	f84b43d3-48eb-422a-88cc-79ed18a1e4d8	ERROR	Error: Cannot find module '@babel/plugin-transform-react-pure-annotations'
Require stack:
- /var/task/node_modules/next-mdx-remote/node_modules/@babel/preset-react/lib/index.js
- /var/task/node_modules/next-mdx-remote/render-to-string.js
- /var/task/.next/server/pages/blog/[slug].js
- /var/task/node_modules/next/dist/next-server/server/require.js
- /var/task/node_modules/next/dist/next-server/server/load-components.js
- /var/task/node_modules/next/dist/next-server/server/api-utils.js
- /var/task/node_modules/next/dist/next-server/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/task/node_modules/next-mdx-remote/node_modules/@babel/preset-react/lib/index.js:16:67)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next-mdx-remote/node_modules/@babel/preset-react/lib/index.js',
    '/var/task/node_modules/next-mdx-remote/render-to-string.js',
    '/var/task/.next/server/pages/blog/[slug].js',
    '/var/task/node_modules/next/dist/next-server/server/require.js',
    '/var/task/node_modules/next/dist/next-server/server/load-components.js',
    '/var/task/node_modules/next/dist/next-server/server/api-utils.js',
    '/var/task/node_modules/next/dist/next-server/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
RequestId: f84b43d3-48eb-422a-88cc-79ed18a1e4d8 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

This was occuring in pro so I installed the lib and it works now
