### ISSUE TITLE
Notes Syntax Highlighting Causing Crash on Lessons

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-next#786]
likely Introduced in #785

something in the markdown and code highlighting is causing a crash with notes code blocks:

http://egghead.af:3000/lessons/react-reorder-a-list-with-react-beautiful-dnd

Was able to reproduce with this lesson.

<img width="1759" alt="Screen Shot 2021-08-01 at 11 01 40 AM" src="https://user-images.githubusercontent.com/86834/127780892-102404f7-459f-40f7-a6de-f381e28e080f.png">

```
index.js?4953:213 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.matchGrammar (index.js?4953:213)
    at Object.tokenize (index.js?4953:320)
    at Highlight.eval [as tokenize] (index.js?dcca:302)
    at Highlight.render (index.js?dcca:320)
    at finishClassComponent (react-dom.development.js?61bb:17485)
    at updateClassComponent (react-dom.development.js?61bb:17435)
    at beginWork (react-dom.development.js?61bb:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:3994)
    at invokeGuardedCallback (react-dom.development.js?61bb:4056)
    at beginWork$1 (react-dom.development.js?61bb:23964)
    at performUnitOfWork (react-dom.development.js?61bb:22776)
    at workLoopSync (react-dom.development.js?61bb:22707)
    at renderRootSync (react-dom.development.js?61bb:22670)
    at performSyncWorkOnRoot (react-dom.development.js?61bb:22293)
    at eval (react-dom.development.js?61bb:11327)
    at unstable_runWithPriority (scheduler.development.js?3069:468)
    at runWithPriority$1 (react-dom.development.js?61bb:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js?61bb:11322)
    at flushSyncCallbackQueue (react-dom.development.js?61bb:11309)
    at scheduleUpdateOnFiber (react-dom.development.js?61bb:21893)
    at dispatchAction (react-dom.development.js?61bb:16139)
    at Object.eval [as next] (useMachine.js?fbbd:60)
    at Interpreter.update (interpreter.js?2cb2:259)
    at eval (interpreter.js?2cb2:104)
    at Scheduler.process (scheduler.js?168e:64)
    at Scheduler.schedule (scheduler.js?168e:43)
    at Interpreter.send (interpreter.js?2cb2:98)
    at _callee2$ ([slug].tsx?488e:355)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?ae0f:3)
    at _next (asyncToGenerator.js?ae0f:25)
matchGrammar @ index.js?4953:213
tokenize @ index.js?4953:320
eval @ index.js?dcca:302
render @ index.js?dcca:320
finishClassComponent @ react-dom.development.js?61bb:17485
updateClassComponent @ react-dom.development.js?61bb:17435
beginWork @ react-dom.development.js?61bb:19073
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
beginWork$1 @ react-dom.development.js?61bb:23964
performUnitOfWork @ react-dom.development.js?61bb:22776
workLoopSync @ react-dom.development.js?61bb:22707
renderRootSync @ react-dom.development.js?61bb:22670
performSyncWorkOnRoot @ react-dom.development.js?61bb:22293
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
scheduleUpdateOnFiber @ react-dom.development.js?61bb:21893
dispatchAction @ react-dom.development.js?61bb:16139
eval @ useMachine.js?fbbd:60
Interpreter.update @ interpreter.js?2cb2:259
eval @ interpreter.js?2cb2:104
Scheduler.process @ scheduler.js?168e:64
Scheduler.schedule @ scheduler.js?168e:43
Interpreter.send @ interpreter.js?2cb2:98
_callee2$ @ [slug].tsx?488e:355
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?ae0f:3
_next @ asyncToGenerator.js?ae0f:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?ae0f:13
_next @ asyncToGenerator.js?ae0f:25
eval @ asyncToGenerator.js?ae0f:32
eval @ asyncToGenerator.js?ae0f:21
_run @ [slug].tsx?488e:349
run @ [slug].tsx?488e:349
eval @ [slug].tsx?488e:374
invokePassiveEffectCreate @ react-dom.development.js?61bb:23487
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
flushPassiveEffectsImpl @ react-dom.development.js?61bb:23574
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushPassiveEffects @ react-dom.development.js?61bb:23447
performSyncWorkOnRoot @ react-dom.development.js?61bb:22269
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
unbatchedUpdates @ react-dom.development.js?61bb:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js?61bb:26020
hydrate @ react-dom.development.js?61bb:26086
renderReactElement @ index.js?20a9:61
doRender @ index.js?20a9:81
_callee2$ @ index.js?20a9:44
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?a954:3
_next @ asyncToGenerator.js?a954:25
eval @ asyncToGenerator.js?a954:32
eval @ asyncToGenerator.js?a954:21
_render @ index.js:525
render @ index.js:462
eval @ next-dev.js?3346:8
eval @ fouc.js?3f0c:4
requestAnimationFrame (async)
displayContent @ fouc.js?3f0c:4
eval @ next-dev.js?3346:8
Promise.then (async)
eval @ next-dev.js?3346:7
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1627840823070:589
options.factory @ webpack.js?ts=1627840823070:675
__webpack_require__ @ webpack.js?ts=1627840823070:37
__webpack_exec__ @ main.js?ts=1627840823070:1356
(anonymous) @ main.js?ts=1627840823070:1357
webpackJsonpCallback @ webpack.js?ts=1627840823070:1255
(anonymous) @ main.js?ts=1627840823070:9
Show 42 more frames
4index.js?dcca:97 Uncaught TypeError: Cannot read property 'type' of undefined
    at normalizeTokens (index.js?dcca:97)
    at Highlight.render (index.js?dcca:321)
    at finishClassComponent (react-dom.development.js?61bb:17485)
    at updateClassComponent (react-dom.development.js?61bb:17435)
    at beginWork (react-dom.development.js?61bb:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:3994)
    at invokeGuardedCallback (react-dom.development.js?61bb:4056)
    at beginWork$1 (react-dom.development.js?61bb:23964)
    at performUnitOfWork (react-dom.development.js?61bb:22776)
    at workLoopSync (react-dom.development.js?61bb:22707)
    at renderRootSync (react-dom.development.js?61bb:22670)
    at performSyncWorkOnRoot (react-dom.development.js?61bb:22293)
    at eval (react-dom.development.js?61bb:11327)
    at unstable_runWithPriority (scheduler.development.js?3069:468)
    at runWithPriority$1 (react-dom.development.js?61bb:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js?61bb:11322)
    at flushSyncCallbackQueue (react-dom.development.js?61bb:11309)
    at scheduleUpdateOnFiber (react-dom.development.js?61bb:21893)
    at dispatchAction (react-dom.development.js?61bb:16139)
    at Object.eval [as next] (useMachine.js?fbbd:60)
    at Interpreter.update (interpreter.js?2cb2:259)
    at eval (interpreter.js?2cb2:104)
    at Scheduler.process (scheduler.js?168e:64)
    at Scheduler.schedule (scheduler.js?168e:43)
    at Interpreter.send (interpreter.js?2cb2:98)
    at _callee2$ ([slug].tsx?488e:355)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?ae0f:3)
    at _next (asyncToGenerator.js?ae0f:25)
normalizeTokens @ index.js?dcca:97
render @ index.js?dcca:321
finishClassComponent @ react-dom.development.js?61bb:17485
updateClassComponent @ react-dom.development.js?61bb:17435
beginWork @ react-dom.development.js?61bb:19073
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
beginWork$1 @ react-dom.development.js?61bb:23964
performUnitOfWork @ react-dom.development.js?61bb:22776
workLoopSync @ react-dom.development.js?61bb:22707
renderRootSync @ react-dom.development.js?61bb:22670
performSyncWorkOnRoot @ react-dom.development.js?61bb:22293
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
scheduleUpdateOnFiber @ react-dom.development.js?61bb:21893
dispatchAction @ react-dom.development.js?61bb:16139
eval @ useMachine.js?fbbd:60
Interpreter.update @ interpreter.js?2cb2:259
eval @ interpreter.js?2cb2:104
Scheduler.process @ scheduler.js?168e:64
Scheduler.schedule @ scheduler.js?168e:43
Interpreter.send @ interpreter.js?2cb2:98
_callee2$ @ [slug].tsx?488e:355
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?ae0f:3
_next @ asyncToGenerator.js?ae0f:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?ae0f:13
_next @ asyncToGenerator.js?ae0f:25
eval @ asyncToGenerator.js?ae0f:32
eval @ asyncToGenerator.js?ae0f:21
_run @ [slug].tsx?488e:349
run @ [slug].tsx?488e:349
eval @ [slug].tsx?488e:374
invokePassiveEffectCreate @ react-dom.development.js?61bb:23487
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
flushPassiveEffectsImpl @ react-dom.development.js?61bb:23574
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushPassiveEffects @ react-dom.development.js?61bb:23447
performSyncWorkOnRoot @ react-dom.development.js?61bb:22269
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
unbatchedUpdates @ react-dom.development.js?61bb:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js?61bb:26020
hydrate @ react-dom.development.js?61bb:26086
renderReactElement @ index.js?20a9:61
doRender @ index.js?20a9:81
_callee2$ @ index.js?20a9:44
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?a954:3
_next @ asyncToGenerator.js?a954:25
eval @ asyncToGenerator.js?a954:32
eval @ asyncToGenerator.js?a954:21
_render @ index.js:525
render @ index.js:462
eval @ next-dev.js?3346:8
eval @ fouc.js?3f0c:4
requestAnimationFrame (async)
displayContent @ fouc.js?3f0c:4
eval @ next-dev.js?3346:8
Promise.then (async)
eval @ next-dev.js?3346:7
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1627840823070:589
options.factory @ webpack.js?ts=1627840823070:675
__webpack_require__ @ webpack.js?ts=1627840823070:37
__webpack_exec__ @ main.js?ts=1627840823070:1356
(anonymous) @ main.js?ts=1627840823070:1357
webpackJsonpCallback @ webpack.js?ts=1627840823070:1255
(anonymous) @ main.js?ts=1627840823070:9
Show 40 more frames
2index.js?4953:213 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.matchGrammar (index.js?4953:213)
    at Object.tokenize (index.js?4953:320)
    at Highlight.eval [as tokenize] (index.js?dcca:302)
    at Highlight.render (index.js?dcca:320)
    at finishClassComponent (react-dom.development.js?61bb:17485)
    at updateClassComponent (react-dom.development.js?61bb:17435)
    at beginWork (react-dom.development.js?61bb:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:3994)
    at invokeGuardedCallback (react-dom.development.js?61bb:4056)
    at beginWork$1 (react-dom.development.js?61bb:23964)
    at performUnitOfWork (react-dom.development.js?61bb:22776)
    at workLoopSync (react-dom.development.js?61bb:22707)
    at renderRootSync (react-dom.development.js?61bb:22670)
    at performSyncWorkOnRoot (react-dom.development.js?61bb:22293)
    at eval (react-dom.development.js?61bb:11327)
    at unstable_runWithPriority (scheduler.development.js?3069:468)
    at runWithPriority$1 (react-dom.development.js?61bb:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js?61bb:11322)
    at flushSyncCallbackQueue (react-dom.development.js?61bb:11309)
    at scheduleUpdateOnFiber (react-dom.development.js?61bb:21893)
    at dispatchAction (react-dom.development.js?61bb:16139)
    at Object.eval [as next] (useMachine.js?fbbd:60)
    at Interpreter.update (interpreter.js?2cb2:259)
    at eval (interpreter.js?2cb2:104)
    at Scheduler.process (scheduler.js?168e:64)
    at Scheduler.schedule (scheduler.js?168e:43)
    at Interpreter.send (interpreter.js?2cb2:98)
    at _callee2$ ([slug].tsx?488e:355)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?ae0f:3)
    at _next (asyncToGenerator.js?ae0f:25)
matchGrammar @ index.js?4953:213
tokenize @ index.js?4953:320
eval @ index.js?dcca:302
render @ index.js?dcca:320
finishClassComponent @ react-dom.development.js?61bb:17485
updateClassComponent @ react-dom.development.js?61bb:17435
beginWork @ react-dom.development.js?61bb:19073
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
beginWork$1 @ react-dom.development.js?61bb:23964
performUnitOfWork @ react-dom.development.js?61bb:22776
workLoopSync @ react-dom.development.js?61bb:22707
renderRootSync @ react-dom.development.js?61bb:22670
performSyncWorkOnRoot @ react-dom.development.js?61bb:22293
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
scheduleUpdateOnFiber @ react-dom.development.js?61bb:21893
dispatchAction @ react-dom.development.js?61bb:16139
eval @ useMachine.js?fbbd:60
Interpreter.update @ interpreter.js?2cb2:259
eval @ interpreter.js?2cb2:104
Scheduler.process @ scheduler.js?168e:64
Scheduler.schedule @ scheduler.js?168e:43
Interpreter.send @ interpreter.js?2cb2:98
_callee2$ @ [slug].tsx?488e:355
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?ae0f:3
_next @ asyncToGenerator.js?ae0f:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?ae0f:13
_next @ asyncToGenerator.js?ae0f:25
eval @ asyncToGenerator.js?ae0f:32
eval @ asyncToGenerator.js?ae0f:21
_run @ [slug].tsx?488e:349
run @ [slug].tsx?488e:349
eval @ [slug].tsx?488e:374
invokePassiveEffectCreate @ react-dom.development.js?61bb:23487
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
flushPassiveEffectsImpl @ react-dom.development.js?61bb:23574
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushPassiveEffects @ react-dom.development.js?61bb:23447
performSyncWorkOnRoot @ react-dom.development.js?61bb:22269
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
unbatchedUpdates @ react-dom.development.js?61bb:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js?61bb:26020
hydrate @ react-dom.development.js?61bb:26086
renderReactElement @ index.js?20a9:61
doRender @ index.js?20a9:81
_callee2$ @ index.js?20a9:44
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?a954:3
_next @ asyncToGenerator.js?a954:25
eval @ asyncToGenerator.js?a954:32
eval @ asyncToGenerator.js?a954:21
_render @ index.js:525
render @ index.js:462
eval @ next-dev.js?3346:8
eval @ fouc.js?3f0c:4
requestAnimationFrame (async)
displayContent @ fouc.js?3f0c:4
eval @ next-dev.js?3346:8
Promise.then (async)
eval @ next-dev.js?3346:7
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1627840823070:589
options.factory @ webpack.js?ts=1627840823070:675
__webpack_require__ @ webpack.js?ts=1627840823070:37
__webpack_exec__ @ main.js?ts=1627840823070:1356
(anonymous) @ main.js?ts=1627840823070:1357
webpackJsonpCallback @ webpack.js?ts=1627840823070:1255
(anonymous) @ main.js?ts=1627840823070:9
Show 42 more frames
7react-dom.development.js?61bb:20085 The above error occurred in the <Highlight> component:

    at Highlight (webpack-internal:///./node_modules/prism-react-renderer/dist/index.js:200:15)
    at CodeBlock (webpack-internal:///./src/components/code-block.tsx:213:23)
    at code
    at div
    at Root (webpack-internal:///./node_modules/react-markdown/lib/renderers.js:51:25)
    at ReactMarkdown (webpack-internal:///./node_modules/react-markdown/lib/react-markdown.js:33:19)
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at eval (webpack-internal:///./node_modules/simplebar-react/dist/simplebar-react.esm.js:161:23)
    at div
    at div
    at div
    at TabPanel (webpack-internal:///./node_modules/@reach/tabs/dist/reach-tabs.esm.js:488:24)
    at NotesTab (webpack-internal:///./src/components/player/player-sidebar.tsx:1389:25)
    at div
    at div
    at DescendantProvider (webpack-internal:///./node_modules/@reach/descendants/dist/reach-descendants.esm.js:142:18)
    at TabPanels (webpack-internal:///./node_modules/@reach/tabs/dist/reach-tabs.esm.js:439:24)
    at div
    at DescendantProvider (webpack-internal:///./node_modules/@reach/descendants/dist/reach-descendants.esm.js:142:18)
    at Tabs (webpack-internal:///./node_modules/@reach/tabs/dist/reach-tabs.esm.js:108:22)
    at div
    at PlayerSidebar (webpack-internal:///./src/components/player/player-sidebar.tsx:1211:28)
    at div
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:46:66)
    at PlayerProvider (webpack-internal:///./node_modules/cueplayer-react/lib/context/player-context.js:38:23)
    at div
    at Lesson (webpack-internal:///./src/pages/lessons/[slug].tsx:6018:28)
    at LessonPage (webpack-internal:///./src/pages/lessons/[slug].tsx:7368:30)
    at div
    at Main (webpack-internal:///./src/components/app/main.tsx:98:23)
    at Layout (webpack-internal:///./src/components/app/layout.tsx:154:23)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:140:46)
    at ConvertkitProvider (webpack-internal:///./src/hooks/use-convertkit.tsx:303:23)
    at CioProvider (webpack-internal:///./src/hooks/use-cio.tsx:466:24)
    at LogRocketProvider (webpack-internal:///./src/hooks/use-logrocket.tsx:1113:23)
    at ViewerProvider (webpack-internal:///./src/context/viewer-context.tsx:2976:25)
    at h (webpack-internal:///./node_modules/next-themes/dist/index.modern.js:10:217)
    at App (webpack-internal:///./src/pages/_app.tsx:793:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:160:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:648:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:784:25)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by joelhooks** [comment]
I tried to use an [error boundary](https://github.com/bvaughn/react-error-boundary) and couldn't figure it out so I punted and just removed syntax highlighting as a hotfix.

**Comment by joelhooks** [comment]
looking at the output with formatting removed, there are a lot of blank/empty code blocks. These are the likely culprits and probably shouldn't exist.

https://egghead.io/lessons/react-reorder-a-list-with-react-beautiful-dnd

![Image 2021-08-01 at 12 01 58 PM](https://user-images.githubusercontent.com/86834/127782397-807ddb51-e62b-462e-b501-c2e9ccfc7ffd.jpg)
